version: '3.9'

services:
  server:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    depends_on:
      - 'server'
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./env/app.env
  mysql:
    depends_on:
      - 'php'
    image: mysql:5.7.32
    env_file:
      - ./env/mysql.env

  # Utility containers
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./env/app.env
    entrypoint: php artisan
  npm:
    image: node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: npm